language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - npm run test

after_script:
  - git init
  - git config user.name "jiangzhixiong"
  - git config user.email "710328466@qq.com"
  - git add .
  - git commit -m "test"
  - git push --force --quiet "https://${test_token}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/j710328466/travis_demo.git